# 개발 환경 특화 설정
services:
  api:
    build:
      dockerfile: Dockerfile.api.dev
    ports:
      - "8000:8000"
    volumes:
      - ./packages/api:/app/packages/api
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: python -m uvicorn packages.api.src.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build:
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    command: npm run dev

  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=maintenance_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=development

  redis:
    ports:
      - "6379:6379"