groups:
  - name: api_alerts
    rules:
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 CPU 사용률"
          description: "CPU 사용률이 80%를 초과했습니다 (현재 값: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: (system_memory_usage_bytes / 1024 / 1024 / 1024) > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 메모리 사용률"
          description: "메모리 사용률이 90%를 초과했습니다 (현재 값: {{ $value | printf \"%.2f\" }}GB)"

      - alert: HighErrorRate
        expr: rate(error_count_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "높은 에러율"
          description: "5분 동안의 에러율이 5%를 초과했습니다"

      - alert: SlowResponseTime
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "느린 응답 시간"
          description: "평균 응답 시간이 2초를 초과했습니다"

      - alert: HighCacheMissRate
        expr: rate(cache_misses_total[5m]) / (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m])) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 캐시 미스율"
          description: "캐시 미스율이 50%를 초과했습니다"

      - alert: DatabaseConnectionsHigh
        expr: db_connections > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 데이터베이스 연결 수"
          description: "데이터베이스 연결 수가 100개를 초과했습니다 (현재 값: {{ $value }})"

      - alert: APIEndpointDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API 엔드포인트 다운"
          description: "API 엔드포인트가 응답하지 않습니다"

      - alert: High4xxErrorRate
        expr: sum(rate(http_requests_total{status_code=~"4.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 4xx 에러율"
          description: "클라이언트 에러(4xx)가 5%를 초과했습니다"

      - alert: High5xxErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.02
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "높은 5xx 에러율"
          description: "서버 에러(5xx)가 2%를 초과했습니다"

      - alert: SlowEndpoint
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "특정 엔드포인트 응답 지연"
          description: "엔드포인트의 평균 응답 시간이 5초를 초과했습니다"

      - alert: HighRequestRate
        expr: sum(rate(http_requests_total[5m])) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 요청률"
          description: "초당 요청 수가 1000을 초과했습니다" 