global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'maintenance-alertmanager:9093'

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'maintenance-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['maintenance-node-exporter:9100'] 